### ISSUE TITLE
'export' pipeline fails when conda env is active

### ISSUE THREAD

**Issue by chg60** [SEA-PHAGES/pdm_utils#1]
python3 -m pdm_utils.run export Actino_Draft ~/Databases/Phamerator/Actino_Draft/Current/ ~/Databases/Phamerator/Actino_Draft/Backups/ ~/PhameratorDB_Management/mysql_queries/

Do you want to export the database from MySQL? yes
MySQL username:
MySQL password:

Do you want to increment the database version number? yes
Old database version: 313
New database version: 314
Database version has been updated.
Creating version file...
Version file has been created.
Dumping new Actino_Draft database to the Main directory...
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) when trying to connect
Traceback (most recent call last):
  File "/home/christian/anaconda3/envs/pdm_utils/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/christian/anaconda3/envs/pdm_utils/lib/python3.7/runpy.py", line 85, in _run_code
    exec(cod, run_globals)
  File "/home/christian/PhameratorDB_Management/pdm_utils/src/pdm_utils/run.py", line 71, in <module>
    main()
  File "/home/christian/PhameratorDB_Management/pdm_utils/src/pdm_utils/run.py", line 59, in main
    export_database.main(sys.argv)
  File "/home/christian/PhameratorDB_Management/pdm_utils/src/pdm_utils/pipelines/db_export/export_database.py", line 255, in main
    proc = subprocess.check_call(command_list, stdout=dumpfile1_handle)
  File "/home/christian/anaconda3/envs/pdm_utils/lib/python3.7/subprocess.py", line347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mysqldump', '-u', 'root', '-pphage', '--skip-comments', 'Actino_Draft']' returned non-zero exit status 2.

**Comment by chg60** [comment]
Problem disappears when conda environment (pdm_utils, generated following instructions in sphinx docs) is deactivated and the mysqldump command uses my system's mysqldump --> suggests the issue lies with whatever mysqldump binary comes with mysql as packaged by Anaconda

**Comment by tmavrich** [comment]
This is probably occurring because you’re running pdm_utils as an installed package. The newest version has not been uploaded to PyPI recently. I’m guessing it will work if you run:

python3 ~/pdm_utils/src/pdm_utils/run.py …




Travis Mavrich
Postdoctoral Researcher
Hatfull Lab
Dept. of Biological Sciences
University of Pittsburgh

On Oct 21, 2019, at 4:10 PM, chg60 <notifications@github.com<mailto:notifications@github.com>> wrote:


Problem disappears when conda environment (pdm_utils, generated following instructions in sphinx docs) is deactivated and the mysqldump command uses my system's mysqldump --> suggests the issue lies with whatever mysqldump binary comes with mysql as packaged by Anaconda

**Comment by chg60** [comment]
It did not work, however removing mysql from the Conda environment solved the issue.  I recommend removing mysql from the Conda environment build command in the docs, since it doesn't eliminate the requirement that users have mysql installed on their machines.
